server:
  port: 8080
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:
    platform: h2
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  profiles:
    active: local
  redis:
    host: 127.0.0.1
    port: 6379
    password:

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

jwt :
  secretkey : yohan
